# fly.toml app configuration file generated for biltongly on 2025-01-27T20:35:18+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'biltongly'
primary_region = 'syd'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'biltongly.fly.dev'
  PORT = '8080'
  DNS_CLUSTER_QUERY = 'biltongly.internal'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
